# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='keep_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='poll_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
    ]
