# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_newuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='password2',
            field=models.CharField(max_length=256),
        ),
    ]
