# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('headImg', models.FileField(upload_to=b'./uploads')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['subject'], 'verbose_name': '\u8bc4\u8bba\u4e3b\u9898', 'verbose_name_plural': '\u8bc4\u8bba\u4e3b\u9898'},
        ),
        migrations.AlterField(
            model_name='remark',
            name='subject',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe4\xb8\xbb\xe9\xa2\x98'),
        ),
    ]
