# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161207_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='headImg',
            field=models.FileField(upload_to=b'./selfuploads'),
        ),
    ]
